import { createApp } from "vue";
import App from "./App.vue";
import router from "./router";
import store from "./store";
import Notifications from "@kyvg/vue3-notification";
import { appAxios } from "@/utils/appAxios";
import {i18n} from "./lang/lang.js";
const app = createApp(App);
app.use(store);
app.use(router);
app.use(Notifications);
app.use(i18n);
app.config.globalProperties.$appAxios = appAxios;
app.mount("#app");
